### ISSUE TITLE
A smaller syntactically valid error throwing expression

### ISSUE THREAD

**Issue by cjwainwright** [getify/let-er#1]
To significantly reduce the download size of the library, the expression `''()` which is used to throw an error could be replaced with `0()`. 

This would need thorough investigation to ensure it is syntactically valid in all environments.

**Comment by getify** [comment]
agreed. investigation necessary. but if `0()` is found to be valid, that would be vastly better than `''()`.

**Comment by getify** [comment]
kind of liking `0=0` if we're going down to 3-character sequences. looks cooler anyway. but still looking for a 1-character or 2-character sequence if any exists.

**Comment by getify** [comment]
So, apparently ES5 defines throwing early (that is, at the syntax level) if it can statically determine it to be an invalid reference. It seems clear that ES5+ implementations could recognize things like `0=0` or `0()` as invalid early, and not allow them to be later caught by the try/catch. :(

Unclear if something like `(void 0)()` would be caught or not. But apparently `(function(x){x()})(1)` should be "safe" in this respect.

More discussion happening on [this twitter thread](https://twitter.com/kangax/status/318802911658397697).

**Comment by getify** [comment]
My guess is that most if not all things on [this crazy page](http://patriciopalladino.com/blog/2012/08/09/non-alphanumeric-javascript.html) would have to be preserved and not disallowed as early optimizations. So far, I think my leading candidate would be:

`[]()`

**Comment by getify** [comment]
I ended up picking `throw void 0` at the suggestion of @allenwb, since it not only guarantees no "early errors" but also ensures that the variable in the catch clause is actually undefined to start out with.
