### ISSUE TITLE
typo in readme, re: let(...)

### ISSUE THREAD

**Issue by rwaldron** [getify/let-er#5]
> ES6 is going to give us the let operator, which will let us do things like let (foo) { .. }

let-statements and let-expressions won't be in ES6

**Comment by rwaldron** [comment]
That's what I get for filing bugs from my phone!

**Comment by getify** [comment]
yeah, this has become more a project to bring `let (..) { .. }` style block-scope to JS even though (for reasons I don't understand) that form was officially rejected. I strongly believe `let (..) { .. }` style block-scope will be easier to read and easier to maintain, so I want to do it that way.

And the bonus is, this form lends itself naturally to my ES3 `try/catch` transpile hack. That means this project brings block-scope to ES3+ whereas `let` itself is quite a bit tougher to transpile right now.

**Comment by rwaldron** [comment]
> let (..) { .. } style block-scope to JS even though (for reasons I don't understand) that form was officially rejected.

Looking into this to find out more, but for now it's only been deferred, which means it will likely be brought up for ES7 http://wiki.ecmascript.org/doku.php?id=strawman:deferred, http://wiki.ecmascript.org/doku.php?id=strawman:let_expressions

I'll post more when I know more

> And the bonus is, this form lends itself naturally to my ES3 try/catch transpile hack.

Traceur uses try/catch as well: http://traceur-compiler.googlecode.com/git/demo/repl.html#function%20f()%20%7B%0A%20%20var%20a%20%3D%201%3B%0A%20%20%0A%20%20%7B%0A%20%20%20%20let%20a%20%3D%202%3B%0A%20%20%7D%0A%20%20%0A%20%20return%20a%3B%0A%7D

(the blockBinding option needs to be on checked for that to work)

**Comment by getify** [comment]
Thanks for the additional info.

I interpreted this tweet to mean it was permanently rejected: https://twitter.com/littlecalculist/status/318728098545811458 I hope maybe it's not quite so permanent, yet. :)

Didn't know about traceur using the try/catch hack. I hadn't heard anyone ever talk about that, thought I was the only one crazy enough to be doing it.

FWIW, they don't handle the `let (..) { .. }` form at all (why should they!?), so my _let-er_ project would stand as the only one doing that, AFAIK. :)

**Comment by rwaldron** [comment]
> I interpreted this tweet to mean it was permanently rejected: https://twitter.com/littlecalculist/status/318728098545811458 I hope maybe it's not quite so permanent, yet. :)

_shrugs_ could be, but it's listed as "deferred" in the document of record, so I'm going with that :)
